version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - reconx-net

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    env_file:
      - .env
    volumes:
      - ./server/data:/app/data
    networks:
      - reconx-net

networks:
  reconx-net:
    driver: bridge
