const express = require('express');
const router = express.Router();
const puppeteer = require('puppeteer');
const calculateRiskScore = require('../utils/riskScore');

// POST /api/export/json
router.post('/json', (req, res) => {
  const { scanResult } = req.body;
  if (!scanResult) return res.status(400).json({ error: "Missing scan data" });

  res.setHeader('Content-Type', 'application/json');
  res.setHeader('Content-Disposition', `attachment; filename=ReconX_Report_${scanResult.target}.json`);
  res.json(scanResult);
});

// POST /api/export/pdf
router.post('/pdf', async (req, res) => {
  const { scanResult } = req.body;
  if (!scanResult) return res.status(400).json({ error: "Missing scan data" });

  const risk = calculateRiskScore(scanResult);

  try {
    const browser = await puppeteer.launch({ headless: 'new', args: ['--no-sandbox'] });
    const page = await browser.newPage();

    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <style>
          body { font-family: 'Helvetica', sans-serif; background: #0f172a; color: white; padding: 40px; }
          .header { border-bottom: 2px solid #06b6d4; padding-bottom: 20px; margin-bottom: 30px; }
          .title { font-size: 24px; font-weight: bold; }
          .target { color: #06b6d4; font-family: monospace; }
          .section { margin-bottom: 40px; }
          h2 { border-left: 4px solid #06b6d4; padding-left: 10px; font-size: 18px; text-transform: uppercase; }
          table { width: 100%; border-collapse: collapse; margin-top: 10px; }
          th, td { text-align: left; padding: 12px; border-bottom: 1px solid #1e293b; font-size: 12px; }
          th { background: #1e293b; color: #94a3b8; text-transform: uppercase; letter-spacing: 1px; }
          .risk-gauge { font-size: 48px; font-weight: 900; color: ${risk.score > 75 ? '#ef4444' : risk.score > 50 ? '#f97316' : '#eab308'}; }
          .badge { padding: 4px 8px; rounded: 4px; font-size: 10px; font-weight: bold; }
          .critical { background: #fee2e2; color: #ef4444; }
          footer { font-size: 10px; color: #94a3b8; text-align: center; margin-top: 50px; }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="title">RECON<span style="color:#06b6d4">X</span> REPORT</div>
          <div style="font-size: 12px; margin-top: 10px;">Generated: ${new Date().toLocaleString()}</div>
          <div class="target">TARGET: ${scanResult.target}</div>
        </div>

        <div class="section">
          <h2>Executive Summary</h2>
          <div style="display: flex; gap: 40px; align-items: center; background: #1e293b; padding: 20px; border-radius: 8px;">
            <div class="risk-gauge">${risk.score}</div>
            <div>
              <p style="margin: 0; font-weight: bold; color: #94a3b8;">OVERALL RISK LEVEL</p>
              <p style="margin: 0; font-size: 20px; font-weight: 900;">${risk.label}</p>
            </div>
          </div>
        </div>

        <div class="section">
          <h2>Ports & Services</h2>
          <table>
            <thead>
              <tr><th>Port</th><th>Protocol</th><th>Service</th><th>Version</th></tr>
            </thead>
            <tbody>
              ${(scanResult.ports || []).map(p => `
                <tr>
                  <td style="color:#06b6d4; font-weight:bold;">${p.port}</td>
                  <td>${p.protocol.toUpperCase()}</td>
                  <td>${p.service}</td>
                  <td>${p.version}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
        </div>

        <div class="section">
          <h2>Vulnerability Analysis (CVEs)</h2>
          ${(scanResult.cves || []).length === 0 ? '<p>No critical vulnerabilities detected.</p>' : `
            <table>
              <thead>
                <tr><th>ID</th><th>Severity</th><th>Score</th><th>Summary</th></tr>
              </thead>
              <tbody>
                ${scanResult.cves.map(c => `
                  <tr>
                    <td style="font-family:monospace; font-weight:bold;">${c.id}</td>
                    <td>${c.severity}</td>
                    <td>${c.cvss}</td>
                    <td style="font-size:10px;">${c.summary}</td>
                  </tr>
                `).join('')}
              </tbody>
            </table>
          `}
        </div>

        <footer>
          Generated by ReconX Ops | Confidential - Authorized Use Only
        </footer>
      </body>
      </html>
    `;

    await page.setContent(htmlContent);
    const pdfBuffer = await page.pdf({ format: 'A4', printBackground: true });
    
    await browser.close();

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=ReconX_Report_${scanResult.target}.pdf`);
    res.send(pdfBuffer);
  } catch (err) {
    console.error("PDF generation failed:", err);
    res.status(500).json({ error: "Failed to generate PDF report" });
  }
});

module.exports = router;
